[project]
name = "test-local-mcp-server-dataquery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=0.3.0",
    "aiosqlite>=0.20.0",
]
